# This script publishes static assets to website

name: Deploy to Production

on: 
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages Archive
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set environment variables
        run: |
            echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
            echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
            
      - name: Publish to archive0-slint
        run: |
            npx wrangler@3 pages deploy . --project-name=archive0-slint
